server:
  port: ${SERVER_PORT:8082}

monegoo:
  service:
    currency: ${CURRENCY_SERVICE:localhost:8080}

  access:
    key: ${ACCESS_KEY}
  push-notification:
    key: ${PUSH_NOTIFICATION_KEY}


spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?zeroDateTimeBehavior=convertToNull
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    properties:
      hibernate: enable_lazy_load_no_trans=true
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update

  # debug sql params
  #spring.jpa.properties.hibernate.format_sql=true
  #logging.level.org.hibernate.type.descriptor.sql=trace






