package com.monegoo.converter.response.crypto;


import com.fasterxml.jackson.annotation.JsonProperty;

import java.math.BigDecimal;

public class CryptoCurrenciesApiResponse {

    public BigDecimal BTC;
    public BigDecimal ETH;
    public BigDecimal USDT;
    public BigDecimal BNB;
    public BigDecimal USDC;
    public BigDecimal XRP;
    public BigDecimal ADA;
    public BigDecimal DOGE;
    public BigDecimal SOL;
    public BigDecimal TRX;
    public BigDecimal LTC;
    public BigDecimal MATIC;
    public BigDecimal DOT;
    public BigDecimal TON;
    public BigDecimal WBTC;
    public BigDecimal DAI;
    public BigDecimal SHIB;
    public BigDecimal AVAX;
    public BigDecimal BUSD;
    public BigDecimal BCH;
    public BigDecimal LEO;
    public BigDecimal LINK;
    public BigDecimal ATOM;
    public BigDecimal TUSD;
    public BigDecimal UNI;
    public BigDecimal XMR;
    public BigDecimal OKB;
    public BigDecimal ETC;
    public BigDecimal XLM;
    public BigDecimal ICP;
    public BigDecimal FIL;
    public BigDecimal LDO;
    public BigDecimal HBAR;
    public BigDecimal APT;
    public BigDecimal CRO;
    public BigDecimal ARB;
    public BigDecimal VET;
    public BigDecimal NEAR;
    public BigDecimal QNT;
    public BigDecimal AAVE;
    public BigDecimal GRT;
    public BigDecimal STX;
    public BigDecimal ALGO;
    public BigDecimal USDP;
    public BigDecimal FTM;
    public BigDecimal EGLD;
    public BigDecimal OP;
    public BigDecimal APE;
    public BigDecimal SAND;
    public BigDecimal EOS;
    public BigDecimal XTZ;
    public BigDecimal BIT;
    public BigDecimal THETA;
    public BigDecimal IMX;
    public BigDecimal RNDR;
    public BigDecimal MANA;
    public BigDecimal RPL;
    public BigDecimal USDD;
    public BigDecimal CFX;
    public BigDecimal MKR;
    public BigDecimal AXS;
    public BigDecimal BSV;
    public BigDecimal KCS;
    public BigDecimal NEO;
    public BigDecimal KAVA;
    public BigDecimal PEPE;
    public BigDecimal CRV;
    public BigDecimal SNX;
    public BigDecimal GALA;
    public BigDecimal FLOW;
    public BigDecimal CHZ;
    public BigDecimal INJ;
    public BigDecimal GUSD;
    public BigDecimal KLAY;
    public BigDecimal LUNC;
    public BigDecimal MIOTA;
    public BigDecimal ZEC;
    public BigDecimal PAXG;
    public BigDecimal GMX;
    public BigDecimal XAUT;
    public BigDecimal XEC;
    public BigDecimal SUI;
    public BigDecimal MINA;
    public BigDecimal BTT;
    public BigDecimal CSPR;
    public BigDecimal XDC;
    public BigDecimal HT;
    public BigDecimal FXS;
    public BigDecimal GT;
    public BigDecimal DASH;
    public BigDecimal TWT;
    public BigDecimal WOO;
    public BigDecimal NEXO;
    public BigDecimal RUNE;
    public BigDecimal ZIL;
    public BigDecimal CAKE;
    public BigDecimal LRC;
    @JsonProperty("1INCH")
    public BigDecimal INCH;
    public BigDecimal ENJ;
    public BigDecimal DYDX;

}